User.create(username: "Johnny", email: "johnny@shanti.com", password: "johnny2020")
User.create(username: "Aakash", email: "Aakash@shanti.com", password: "Aakash2020")
User.create(username: "Rahul", email: "Rahul@shanti.com", password: "rahul2020")
User.create(username: "Elani", email: "Elani@shanti.com", password: "elani27") 
User.create(username: "Niya", email: "niya18@shanti.com", password: "niya18") 